sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

matrix:
  fast_finish: true

env:
  global:
    - secure: oc86/M958dO1HlcqIzOQ8vFFZARAZlKwGdIwEQRKiH+UhYLyNZCI9Y64IbHKs7n+2CCh13II4kU+iSgdClXfOA6S9nDBYIzzxbEiNviAfJCWbn0kth6mZ3n4rMd5tOvcaIZwSIa6f3w8l5PBLOohcdb9/1YUPiD1KO+ioKXgMZPm/PeLL8CQbPn2oeW2unzhrypJDhYdb/KRYRCMGPtQVmAjx5UhMGBTfP26t8rWLueq+dSKNuCRK/xzXM+CW1/h/ZvARpSqKoJHKElWzmaOnRbcSOBo5Mxj4SkZM2jq80aWfXL6n8UdW2WyQsz9W/8yYAQs4f8rWRNWXxHeFDOpofEzLO89rbOFPriTQJJJwZLeXIbmBGEcGz8v+gJvbhFzh2MRZKpDHf3KEemagfaMSyGB04KrCKmYKXo0iTPJKwAKRqB7g6r+nFpdWw9/TjPfKKsrljW8NJ+qvyVaKRuva0O/K8FuzjDbnDNaxq4A9Lr9qdzDt0acUc3JyanlLHzDGorZWq2FYOCrU0Wpt1M2EvPN/aA3QJuCFaa1OxZvXpXyugxbAkCOfdLXDLrj8LpWDX9qrIsAnG3B2HDq6TDmb1TTw31oEN3NroclvE9YQiyl4KDOTjxJZYr/6J+jTN1KOcul/2Eg09djP4ePW4lR3Q3qlXrac63RhogC8xp0LL8
    - COVERALLS_SERVICE_NAME=travis-ci
